#https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
name: notify-force-push
on:
  push:
    branches:
        - main
jobs:
  notify:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    env:
        AUTHOR: ${{ github.event.pusher.name }}
    steps:
      - name: notify
        run: echo "${AUTHOR}"
      - name: notify slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
            # Slack channel id, channel name, or user id to post message.
            # See also: https://api.slack.com/methods/chat.postMessage#channels
            channel-id: 'develop-direct-pushes'
            # For posting a rich message using Block Kit
            payload: |
                {
                    "text": " ${{ github.event.head_commit.url }}",
                    "blocks": [
                    {
                        "type": "section",
                        "text": {
                        "type": "mrkdwn",
                        "text": "AHHHHHHHHH! ${{ github.event.head_commit.url }}"
                        }
                    }
                    ]
                }
        env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
