#https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
name: notify-force-push
on:
  push:
jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: notify
        run: echo "${{ github.event.sender }}"
